name: Python DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  # ========================================
  # 1. UNIT TEST
  # ========================================

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: |
          pytest --cov=app --cov-report=term-missing


  # ========================================
  # 2. SAST
  # ========================================

  sast:
    name: SAST - CodeQL
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Analyze code
        uses: github/codeql-action/analyze@v3


  # ========================================
  # 3. SCA
  # ========================================

  sca:
    name: SCA - Dependency Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit

      - name: Run dependency scan
        run: |
          pip-audit


  # ========================================
  # 4. DOCKER BUILD
  # ========================================

  docker-build:
    name: Docker Build
    needs:
      - test
      - sast
      - sca

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build \
            -t session17-python:${{ github.sha }} .


  # ========================================
  # 5. IMAGE SCAN
  # ========================================

  image-scan:
    name: Container Image Scan
    needs:
      - docker-build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build image
        run: |
          docker build \
            -t session17-python:${{ github.sha }} .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | sudo gpg --dearmor \
            -o /usr/share/keyrings/trivy.gpg

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] \
            https://aquasecurity.github.io/trivy-repo/deb \
            generic main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan image
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            session17-python:${{ github.sha }}


  # ========================================
  # 6. PUSH TO GHCR
  # ========================================

  push:
    name: Push Image to GHCR

    needs:
      - image-scan

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push image
        run: |
          docker push \
            ghcr.io/${{ github.repository }}:${{ github.sha }}